# The Site Configuration

theme: jekyll-theme-chirpy

lang: en

timezone: America/Toronto

title: irishlab.io

tagline: Personal homelab

description: >-
  where I learn Architecture, Infrastructure, Networking, DevOps, and a few others things.

url: ""

github:
  username: irish1986

social:
  name: Simon HARVEY
  email: simon.harvey.86@gmail.com
  links:
    - https://github.com/irish1986
    - https://www.linkedin.com/in/simon-harvey-a0305029/

google_site_verification:

google_analytics:
  id:

theme_mode:

img_cdn:

avatar: https://avatars.githubusercontent.com/u/13018674?v=4

toc: true

comments:
  active:
  disqus:
    shortname:
  utterances:
    repo:
    issue_term:
  giscus:
    repo:
    repo_id:
    category:
    category_id:
    mapping:
    input_position:
    lang:
    reactions_enabled:


assets:
  self_host:
    enabled:
    env:

pwa:
  enabled: true

paginate: 10

baseurl: ""

kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: highlight
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

collections:
  tabs:
    output: true
    sort_by: order

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      comments: true
      toc: true
      permalink: /posts/:title/
  - scope:
      path: _drafts
    values:
      comments: false
  - scope:
      path: ""
      type: tabs
    values:
      layout: page
      permalink: /:title/
  - scope:
      path: assets/img/favicons
    values:
      swcache: true
  - scope:
      path: assets/js/dist
    values:
      swcache: true

sass:
  style: compressed

compress_html:
  clippings: all
  comments: all
  endings: all
  profile: false
  blanklines: false
  ignore:
    envs: [development]

exclude:
  - .pre-commit-config.yaml
  - "*.gem"
  - "*.gemspec"
  - /.taskfile
  - Dockerfile
  - docs
  - LICENSE
  - package*.json
  - README.Docker.md
  - README.md
  - rollup.config.js
  - Taskfile.yml
  - tools

jekyll-archives:
  enabled: [categories, tags]
  layouts:
    category: category
    tag: tag
  permalinks:
    tag: /tags/:name/
    category: /categories/:name/
